# Generated by Django 4.2.3 on 2023-07-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=14)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.IntegerField(default=91)),
                ('age', models.IntegerField(default=0)),
                ('department', models.CharField(default='', max_length=30)),
                ('role', models.CharField(default='', max_length=30)),
                ('salary', models.FloatField(default=0.0)),
                ('leaves', models.IntegerField(default=0)),
                ('joinDate', models.DateField(default='django.utils.timezone.now')),
                ('status', models.CharField(default='Inactive', max_length=10)),
            ],
        ),
    ]
