# Generated by Django 4.2.3 on 2023-07-18 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joinDate',
            field=models.DateField(default=datetime.date(2023, 7, 18)),
        ),
    ]
