# Generated by Django 5.0.1 on 2024-01-26 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_alter_employee_joindate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='joinDate',
            field=models.DateField(default=datetime.date(2024, 1, 27)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=models.BigIntegerField(default=91),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
